package SimpleCalculatorApp;


/**
* SimpleCalculatorApp/SimpleCalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimpleCalculator.idl
* Sábado, 10 de Novembro de 2018 11h08min11s BRT
*/

public interface SimpleCalculatorOperations 
{
  double sumNumbers (double number1, double number2);
  void shutdown ();
} // interface SimpleCalculatorOperations
