package SimpleCalculatorApp;


/**
* SimpleCalculatorApp/SimpleCalculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimpleCalculator.idl
* Sábado, 10 de Novembro de 2018 11h08min11s BRT
*/

public interface SimpleCalculator extends SimpleCalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SimpleCalculator
