package SimpleCalculatorApp;

/**
* SimpleCalculatorApp/SimpleCalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimpleCalculator.idl
* Sábado, 10 de Novembro de 2018 11h08min11s BRT
*/

public final class SimpleCalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public SimpleCalculatorApp.SimpleCalculator value = null;

  public SimpleCalculatorHolder ()
  {
  }

  public SimpleCalculatorHolder (SimpleCalculatorApp.SimpleCalculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SimpleCalculatorApp.SimpleCalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SimpleCalculatorApp.SimpleCalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SimpleCalculatorApp.SimpleCalculatorHelper.type ();
  }

}
