package SimpleCalculatorApp;


/**
* SimpleCalculatorApp/SimpleCalculatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimpleCalculator.idl
* Sábado, 10 de Novembro de 2018 11h08min11s BRT
*/

public abstract class SimpleCalculatorPOA extends org.omg.PortableServer.Servant
 implements SimpleCalculatorApp.SimpleCalculatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sumNumbers", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SimpleCalculatorApp/SimpleCalculator/sumNumbers
       {
         double number1 = in.read_double ();
         double number2 = in.read_double ();
         double $result = (double)0;
         $result = this.sumNumbers (number1, number2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // SimpleCalculatorApp/SimpleCalculator/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SimpleCalculatorApp/SimpleCalculator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SimpleCalculator _this() 
  {
    return SimpleCalculatorHelper.narrow(
    super._this_object());
  }

  public SimpleCalculator _this(org.omg.CORBA.ORB orb) 
  {
    return SimpleCalculatorHelper.narrow(
    super._this_object(orb));
  }


} // class SimpleCalculatorPOA
